name: DNV.ApiClients.Veracity.Identity.InternalPlatformApiV4

on:
  workflow_dispatch:
    inputs:
      require_publish:
        type: boolean
        default: false
  push:
    branches:
    - main
    paths:
    - 'src/InternalPlatformApiV4/**'
    - '.github/workflows/InternalPlatformApiV4.yml'
  pull_request:
    types: [ closed ]
    paths:
    - 'src/InternalPlatformApiV4/**'
    - '.github/workflows/InternalPlatformApiV4.yml'
jobs:
  autorest-generate:
    uses: ./.github/workflows/autorest-generate.yml
    with:
      config-file: assets/InternalPlatformApiV4.md
      project-name: DNV.ApiClients.Veracity.Identity.InternalPlatformApiV4.ApiClient
      output-folder: src/DNV.ApiClients.Veracity.Identity.InternalPlatformApiV4
  nuget-publish:
    needs: autorest-generate
    uses: ./.github/workflows/nuget-publish.yml
    with:
      source-path: src/DNV.ApiClients.Veracity.Identity.InternalPlatformApiV4
      project-name: DNV.ApiClients.Veracity.Identity.InternalPlatformApiV4
      require_publish: ${{ inputs.require_publish == true || inputs.require_publish == 'true'}}
    secrets: inherit
